// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://fouehqfnbzeqpbyntziz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvdWVocWZuYnplcXBieW50eml6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5NDA0NzQsImV4cCI6MjA3ODUxNjQ3NH0.2FOvjSZQ5MIzQIcQBHD25-gQnSuj4gVX6r0Qnbz4qrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);